### ISSUE TITLE
Collection of small ToDos

### ISSUE THREAD

**Issue by TheRadialActive** [sdaps/website#2]
- [x] moving fontawesome icons to theme
  - [x] all icons in the theme should be fontawesome
- [x] check all the links
  - [x] "doc_" -links
- [x] implement logo (also favicon)
- [x] implement/link [video](https://media.ccc.de/v/froscon2015-1606-sdaps ) (maybe with placeholder img)
- [x] fix shortcode for buttons
  - [x] add shortcode buttons to important pages (like "Getting Started"), explicitly on the frontpage
- [x] fontawesome 
- [x] remove CDNs in theme if available (Github will stay)
  - [x] googlefonts optional/Roboto fonts integrated
  - [x] highlightjs implemented
- [x] add irc and matrix link in the right head corner (maybe link to mailinglist)

**Comment by DerMolly** [comment]
- [x]  moving fontawesome icons to theme
- [x]  implement logo (also favicon)

**Comment by benzea** [comment]
Closing as everything has been done. Thanks for the work!

A new issue can always be created :)
